# Keycloak 23 avec le theme de connexion LINSOFT integre
# Build : docker build -t quay.io/akh901736/keycloak-linsoft:latest ./keycloak
FROM quay.io/keycloak/keycloak:23.0.0

# Copie le theme personnalise (login LINSOFT) dans le repertoire des themes
COPY themes /opt/keycloak/themes
