server:
  port: 8080

spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/**
        - id: event-service
          uri: lb://event-service
          predicates:
            - Path=/api/events/**
        - id: registration-service
          uri: lb://registration-service
          predicates:
            - Path=/api/registrations/**
        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/api/notifications/**
        - id: ticket-service
          uri: lb://ticket-service
          predicates:
            - Path=/api/tickets/**
        - id: feedback-service
          uri: lb://feedback-service
          predicates:
            - Path=/api/feedback/**
        - id: ai-service
          uri: lb://ai-service
          predicates:
            - Path=/api/ai/**
