server:
  port: 8082

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/event_db
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USER:guest}
    password: ${RABBITMQ_PASSWORD:guest}
